language: ruby
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - GIT_NAME=hyunjong-lee
  - GIT_EMAIL=hyunjong.lee.s@gmail.com
  - secure: E5+qY+R02UsFvITzB2WxAy0M0pQQCKMQTWFPxVPnEka1vGTjOUy0qhyoh6Q32fqWjN4q3w2xkLMXmYboLFgNwGcJHGaZsmgPjkLNgVuKpOlHCbsv2cbD315yLQoBY3LmJ1Mkry7q/vwYPnC1jAngI6zmW5SObzzOwJNsuc7gQec=
