language: ruby
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - GIT_NAME=hyunjong-lee
  - GIT_EMAIL=hyunjong.lee.s@gmail.com
  - secure: Zg9lv+tdahTiFtPgisf0e8uMoEqJ32Sp7Dsia7C6hDVC6UbmS3jSvHe2VC6rhvyj7aOv5ChXTVPMr+nyswrpfCQ1N78w6XC9V5Vo+93vVqdFbshfN4zacWLmMByqr4zOh2qvM8h/YuI58tyBFw4G2OInUf5xH/Ka+I9flNaL+0M=
