url: http://hyunjong-lee.github.io
baseurl: /
username: hyunjong-lee
repo: hyunjong-lee.github.io
branch: jekyll
relative_source: .
destination: ../site-deploy/

name: Human Learning
description: Learning Anything or Nothing
meta_description: "Human Learning & Machine Learning"

markdown: redcarpet
highlighter: pygments
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - strikethrough
    - superscript
    - tables

logo: true
paginate: 15
domain_name: 'http://hyunjong-lee.github.io'

# Details for the RSS feed generator
url:            'http://hyunjong-lee.github.io'
author:         'Peter'

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
  - TokenGenerator
